# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/laura/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/laura/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/laura/Documents/course_os

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/laura/Documents/course_os

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/laura/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/laura/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laura/Documents/course_os/CMakeFiles /home/laura/Documents/course_os/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/laura/Documents/course_os/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named course_os

# Build rule for target.
course_os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 course_os
.PHONY : course_os

# fast build rule for target.
course_os/fast:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/build
.PHONY : course_os/fast

kernel/src/allocator/allocator.o: kernel/src/allocator/allocator.c.o

.PHONY : kernel/src/allocator/allocator.o

# target to build an object file
kernel/src/allocator/allocator.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/allocator.c.o
.PHONY : kernel/src/allocator/allocator.c.o

kernel/src/allocator/allocator.i: kernel/src/allocator/allocator.c.i

.PHONY : kernel/src/allocator/allocator.i

# target to preprocess a source file
kernel/src/allocator/allocator.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/allocator.c.i
.PHONY : kernel/src/allocator/allocator.c.i

kernel/src/allocator/allocator.s: kernel/src/allocator/allocator.c.s

.PHONY : kernel/src/allocator/allocator.s

# target to generate assembly for a file
kernel/src/allocator/allocator.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/allocator.c.s
.PHONY : kernel/src/allocator/allocator.c.s

kernel/src/allocator/llist.o: kernel/src/allocator/llist.c.o

.PHONY : kernel/src/allocator/llist.o

# target to build an object file
kernel/src/allocator/llist.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/llist.c.o
.PHONY : kernel/src/allocator/llist.c.o

kernel/src/allocator/llist.i: kernel/src/allocator/llist.c.i

.PHONY : kernel/src/allocator/llist.i

# target to preprocess a source file
kernel/src/allocator/llist.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/llist.c.i
.PHONY : kernel/src/allocator/llist.c.i

kernel/src/allocator/llist.s: kernel/src/allocator/llist.c.s

.PHONY : kernel/src/allocator/llist.s

# target to generate assembly for a file
kernel/src/allocator/llist.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/llist.c.s
.PHONY : kernel/src/allocator/llist.c.s

kernel/src/allocator/mem_alloc.o: kernel/src/allocator/mem_alloc.c.o

.PHONY : kernel/src/allocator/mem_alloc.o

# target to build an object file
kernel/src/allocator/mem_alloc.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/mem_alloc.c.o
.PHONY : kernel/src/allocator/mem_alloc.c.o

kernel/src/allocator/mem_alloc.i: kernel/src/allocator/mem_alloc.c.i

.PHONY : kernel/src/allocator/mem_alloc.i

# target to preprocess a source file
kernel/src/allocator/mem_alloc.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/mem_alloc.c.i
.PHONY : kernel/src/allocator/mem_alloc.c.i

kernel/src/allocator/mem_alloc.s: kernel/src/allocator/mem_alloc.c.s

.PHONY : kernel/src/allocator/mem_alloc.s

# target to generate assembly for a file
kernel/src/allocator/mem_alloc.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/mem_alloc.c.s
.PHONY : kernel/src/allocator/mem_alloc.c.s

kernel/src/allocator/test/test_allocator.o: kernel/src/allocator/test/test_allocator.c.o

.PHONY : kernel/src/allocator/test/test_allocator.o

# target to build an object file
kernel/src/allocator/test/test_allocator.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/test/test_allocator.c.o
.PHONY : kernel/src/allocator/test/test_allocator.c.o

kernel/src/allocator/test/test_allocator.i: kernel/src/allocator/test/test_allocator.c.i

.PHONY : kernel/src/allocator/test/test_allocator.i

# target to preprocess a source file
kernel/src/allocator/test/test_allocator.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/test/test_allocator.c.i
.PHONY : kernel/src/allocator/test/test_allocator.c.i

kernel/src/allocator/test/test_allocator.s: kernel/src/allocator/test/test_allocator.c.s

.PHONY : kernel/src/allocator/test/test_allocator.s

# target to generate assembly for a file
kernel/src/allocator/test/test_allocator.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/allocator/test/test_allocator.c.s
.PHONY : kernel/src/allocator/test/test_allocator.c.s

kernel/src/common/hardwareinfo.o: kernel/src/common/hardwareinfo.c.o

.PHONY : kernel/src/common/hardwareinfo.o

# target to build an object file
kernel/src/common/hardwareinfo.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/hardwareinfo.c.o
.PHONY : kernel/src/common/hardwareinfo.c.o

kernel/src/common/hardwareinfo.i: kernel/src/common/hardwareinfo.c.i

.PHONY : kernel/src/common/hardwareinfo.i

# target to preprocess a source file
kernel/src/common/hardwareinfo.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/hardwareinfo.c.i
.PHONY : kernel/src/common/hardwareinfo.c.i

kernel/src/common/hardwareinfo.s: kernel/src/common/hardwareinfo.c.s

.PHONY : kernel/src/common/hardwareinfo.s

# target to generate assembly for a file
kernel/src/common/hardwareinfo.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/hardwareinfo.c.s
.PHONY : kernel/src/common/hardwareinfo.c.s

kernel/src/common/interrupt.o: kernel/src/common/interrupt.c.o

.PHONY : kernel/src/common/interrupt.o

# target to build an object file
kernel/src/common/interrupt.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/interrupt.c.o
.PHONY : kernel/src/common/interrupt.c.o

kernel/src/common/interrupt.i: kernel/src/common/interrupt.c.i

.PHONY : kernel/src/common/interrupt.i

# target to preprocess a source file
kernel/src/common/interrupt.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/interrupt.c.i
.PHONY : kernel/src/common/interrupt.c.i

kernel/src/common/interrupt.s: kernel/src/common/interrupt.c.s

.PHONY : kernel/src/common/interrupt.s

# target to generate assembly for a file
kernel/src/common/interrupt.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/interrupt.c.s
.PHONY : kernel/src/common/interrupt.c.s

kernel/src/common/start.o: kernel/src/common/start.c.o

.PHONY : kernel/src/common/start.o

# target to build an object file
kernel/src/common/start.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/start.c.o
.PHONY : kernel/src/common/start.c.o

kernel/src/common/start.i: kernel/src/common/start.c.i

.PHONY : kernel/src/common/start.i

# target to preprocess a source file
kernel/src/common/start.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/start.c.i
.PHONY : kernel/src/common/start.c.i

kernel/src/common/start.s: kernel/src/common/start.c.s

.PHONY : kernel/src/common/start.s

# target to generate assembly for a file
kernel/src/common/start.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/common/start.c.s
.PHONY : kernel/src/common/start.c.s

kernel/src/drivers/chipset/bcm2835/bcm2835.o: kernel/src/drivers/chipset/bcm2835/bcm2835.c.o

.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.o

# target to build an object file
kernel/src/drivers/chipset/bcm2835/bcm2835.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2835/bcm2835.c.o
.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.c.o

kernel/src/drivers/chipset/bcm2835/bcm2835.i: kernel/src/drivers/chipset/bcm2835/bcm2835.c.i

.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.i

# target to preprocess a source file
kernel/src/drivers/chipset/bcm2835/bcm2835.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2835/bcm2835.c.i
.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.c.i

kernel/src/drivers/chipset/bcm2835/bcm2835.s: kernel/src/drivers/chipset/bcm2835/bcm2835.c.s

.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.s

# target to generate assembly for a file
kernel/src/drivers/chipset/bcm2835/bcm2835.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2835/bcm2835.c.s
.PHONY : kernel/src/drivers/chipset/bcm2835/bcm2835.c.s

kernel/src/drivers/chipset/bcm2836/bcm2836.o: kernel/src/drivers/chipset/bcm2836/bcm2836.c.o

.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.o

# target to build an object file
kernel/src/drivers/chipset/bcm2836/bcm2836.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/bcm2836.c.o
.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.c.o

kernel/src/drivers/chipset/bcm2836/bcm2836.i: kernel/src/drivers/chipset/bcm2836/bcm2836.c.i

.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.i

# target to preprocess a source file
kernel/src/drivers/chipset/bcm2836/bcm2836.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/bcm2836.c.i
.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.c.i

kernel/src/drivers/chipset/bcm2836/bcm2836.s: kernel/src/drivers/chipset/bcm2836/bcm2836.c.s

.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.s

# target to generate assembly for a file
kernel/src/drivers/chipset/bcm2836/bcm2836.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/bcm2836.c.s
.PHONY : kernel/src/drivers/chipset/bcm2836/bcm2836.c.s

kernel/src/drivers/chipset/bcm2836/timer.o: kernel/src/drivers/chipset/bcm2836/timer.c.o

.PHONY : kernel/src/drivers/chipset/bcm2836/timer.o

# target to build an object file
kernel/src/drivers/chipset/bcm2836/timer.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/timer.c.o
.PHONY : kernel/src/drivers/chipset/bcm2836/timer.c.o

kernel/src/drivers/chipset/bcm2836/timer.i: kernel/src/drivers/chipset/bcm2836/timer.c.i

.PHONY : kernel/src/drivers/chipset/bcm2836/timer.i

# target to preprocess a source file
kernel/src/drivers/chipset/bcm2836/timer.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/timer.c.i
.PHONY : kernel/src/drivers/chipset/bcm2836/timer.c.i

kernel/src/drivers/chipset/bcm2836/timer.s: kernel/src/drivers/chipset/bcm2836/timer.c.s

.PHONY : kernel/src/drivers/chipset/bcm2836/timer.s

# target to generate assembly for a file
kernel/src/drivers/chipset/bcm2836/timer.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/timer.c.s
.PHONY : kernel/src/drivers/chipset/bcm2836/timer.c.s

kernel/src/drivers/chipset/bcm2836/uart.o: kernel/src/drivers/chipset/bcm2836/uart.c.o

.PHONY : kernel/src/drivers/chipset/bcm2836/uart.o

# target to build an object file
kernel/src/drivers/chipset/bcm2836/uart.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/uart.c.o
.PHONY : kernel/src/drivers/chipset/bcm2836/uart.c.o

kernel/src/drivers/chipset/bcm2836/uart.i: kernel/src/drivers/chipset/bcm2836/uart.c.i

.PHONY : kernel/src/drivers/chipset/bcm2836/uart.i

# target to preprocess a source file
kernel/src/drivers/chipset/bcm2836/uart.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/uart.c.i
.PHONY : kernel/src/drivers/chipset/bcm2836/uart.c.i

kernel/src/drivers/chipset/bcm2836/uart.s: kernel/src/drivers/chipset/bcm2836/uart.c.s

.PHONY : kernel/src/drivers/chipset/bcm2836/uart.s

# target to generate assembly for a file
kernel/src/drivers/chipset/bcm2836/uart.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/bcm2836/uart.c.s
.PHONY : kernel/src/drivers/chipset/bcm2836/uart.c.s

kernel/src/drivers/chipset/chipset.o: kernel/src/drivers/chipset/chipset.c.o

.PHONY : kernel/src/drivers/chipset/chipset.o

# target to build an object file
kernel/src/drivers/chipset/chipset.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/chipset.c.o
.PHONY : kernel/src/drivers/chipset/chipset.c.o

kernel/src/drivers/chipset/chipset.i: kernel/src/drivers/chipset/chipset.c.i

.PHONY : kernel/src/drivers/chipset/chipset.i

# target to preprocess a source file
kernel/src/drivers/chipset/chipset.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/chipset.c.i
.PHONY : kernel/src/drivers/chipset/chipset.c.i

kernel/src/drivers/chipset/chipset.s: kernel/src/drivers/chipset/chipset.c.s

.PHONY : kernel/src/drivers/chipset/chipset.s

# target to generate assembly for a file
kernel/src/drivers/chipset/chipset.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/chipset/chipset.c.s
.PHONY : kernel/src/drivers/chipset/chipset.c.s

kernel/src/drivers/mmci/mmci.o: kernel/src/drivers/mmci/mmci.c.o

.PHONY : kernel/src/drivers/mmci/mmci.o

# target to build an object file
kernel/src/drivers/mmci/mmci.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/mmci/mmci.c.o
.PHONY : kernel/src/drivers/mmci/mmci.c.o

kernel/src/drivers/mmci/mmci.i: kernel/src/drivers/mmci/mmci.c.i

.PHONY : kernel/src/drivers/mmci/mmci.i

# target to preprocess a source file
kernel/src/drivers/mmci/mmci.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/mmci/mmci.c.i
.PHONY : kernel/src/drivers/mmci/mmci.c.i

kernel/src/drivers/mmci/mmci.s: kernel/src/drivers/mmci/mmci.c.s

.PHONY : kernel/src/drivers/mmci/mmci.s

# target to generate assembly for a file
kernel/src/drivers/mmci/mmci.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/drivers/mmci/mmci.c.s
.PHONY : kernel/src/drivers/mmci/mmci.c.s

kernel/src/ds/bpf/HashMap.o: kernel/src/ds/bpf/HashMap.c.o

.PHONY : kernel/src/ds/bpf/HashMap.o

# target to build an object file
kernel/src/ds/bpf/HashMap.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/HashMap.c.o
.PHONY : kernel/src/ds/bpf/HashMap.c.o

kernel/src/ds/bpf/HashMap.i: kernel/src/ds/bpf/HashMap.c.i

.PHONY : kernel/src/ds/bpf/HashMap.i

# target to preprocess a source file
kernel/src/ds/bpf/HashMap.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/HashMap.c.i
.PHONY : kernel/src/ds/bpf/HashMap.c.i

kernel/src/ds/bpf/HashMap.s: kernel/src/ds/bpf/HashMap.c.s

.PHONY : kernel/src/ds/bpf/HashMap.s

# target to generate assembly for a file
kernel/src/ds/bpf/HashMap.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/HashMap.c.s
.PHONY : kernel/src/ds/bpf/HashMap.c.s

kernel/src/ds/bpf/test/hashmap_test.o: kernel/src/ds/bpf/test/hashmap_test.c.o

.PHONY : kernel/src/ds/bpf/test/hashmap_test.o

# target to build an object file
kernel/src/ds/bpf/test/hashmap_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/test/hashmap_test.c.o
.PHONY : kernel/src/ds/bpf/test/hashmap_test.c.o

kernel/src/ds/bpf/test/hashmap_test.i: kernel/src/ds/bpf/test/hashmap_test.c.i

.PHONY : kernel/src/ds/bpf/test/hashmap_test.i

# target to preprocess a source file
kernel/src/ds/bpf/test/hashmap_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/test/hashmap_test.c.i
.PHONY : kernel/src/ds/bpf/test/hashmap_test.c.i

kernel/src/ds/bpf/test/hashmap_test.s: kernel/src/ds/bpf/test/hashmap_test.c.s

.PHONY : kernel/src/ds/bpf/test/hashmap_test.s

# target to generate assembly for a file
kernel/src/ds/bpf/test/hashmap_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/bpf/test/hashmap_test.c.s
.PHONY : kernel/src/ds/bpf/test/hashmap_test.c.s

kernel/src/ds/priority_queue.o: kernel/src/ds/priority_queue.c.o

.PHONY : kernel/src/ds/priority_queue.o

# target to build an object file
kernel/src/ds/priority_queue.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/priority_queue.c.o
.PHONY : kernel/src/ds/priority_queue.c.o

kernel/src/ds/priority_queue.i: kernel/src/ds/priority_queue.c.i

.PHONY : kernel/src/ds/priority_queue.i

# target to preprocess a source file
kernel/src/ds/priority_queue.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/priority_queue.c.i
.PHONY : kernel/src/ds/priority_queue.c.i

kernel/src/ds/priority_queue.s: kernel/src/ds/priority_queue.c.s

.PHONY : kernel/src/ds/priority_queue.s

# target to generate assembly for a file
kernel/src/ds/priority_queue.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/priority_queue.c.s
.PHONY : kernel/src/ds/priority_queue.c.s

kernel/src/ds/qstr.o: kernel/src/ds/qstr.c.o

.PHONY : kernel/src/ds/qstr.o

# target to build an object file
kernel/src/ds/qstr.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/qstr.c.o
.PHONY : kernel/src/ds/qstr.c.o

kernel/src/ds/qstr.i: kernel/src/ds/qstr.c.i

.PHONY : kernel/src/ds/qstr.i

# target to preprocess a source file
kernel/src/ds/qstr.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/qstr.c.i
.PHONY : kernel/src/ds/qstr.c.i

kernel/src/ds/qstr.s: kernel/src/ds/qstr.c.s

.PHONY : kernel/src/ds/qstr.s

# target to generate assembly for a file
kernel/src/ds/qstr.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/qstr.c.s
.PHONY : kernel/src/ds/qstr.c.s

kernel/src/ds/test/priority_queue_test.o: kernel/src/ds/test/priority_queue_test.c.o

.PHONY : kernel/src/ds/test/priority_queue_test.o

# target to build an object file
kernel/src/ds/test/priority_queue_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/priority_queue_test.c.o
.PHONY : kernel/src/ds/test/priority_queue_test.c.o

kernel/src/ds/test/priority_queue_test.i: kernel/src/ds/test/priority_queue_test.c.i

.PHONY : kernel/src/ds/test/priority_queue_test.i

# target to preprocess a source file
kernel/src/ds/test/priority_queue_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/priority_queue_test.c.i
.PHONY : kernel/src/ds/test/priority_queue_test.c.i

kernel/src/ds/test/priority_queue_test.s: kernel/src/ds/test/priority_queue_test.c.s

.PHONY : kernel/src/ds/test/priority_queue_test.s

# target to generate assembly for a file
kernel/src/ds/test/priority_queue_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/priority_queue_test.c.s
.PHONY : kernel/src/ds/test/priority_queue_test.c.s

kernel/src/ds/test/qstr_test.o: kernel/src/ds/test/qstr_test.c.o

.PHONY : kernel/src/ds/test/qstr_test.o

# target to build an object file
kernel/src/ds/test/qstr_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/qstr_test.c.o
.PHONY : kernel/src/ds/test/qstr_test.c.o

kernel/src/ds/test/qstr_test.i: kernel/src/ds/test/qstr_test.c.i

.PHONY : kernel/src/ds/test/qstr_test.i

# target to preprocess a source file
kernel/src/ds/test/qstr_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/qstr_test.c.i
.PHONY : kernel/src/ds/test/qstr_test.c.i

kernel/src/ds/test/qstr_test.s: kernel/src/ds/test/qstr_test.c.s

.PHONY : kernel/src/ds/test/qstr_test.s

# target to generate assembly for a file
kernel/src/ds/test/qstr_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/qstr_test.c.s
.PHONY : kernel/src/ds/test/qstr_test.c.s

kernel/src/ds/test/u8_array_list_test.o: kernel/src/ds/test/u8_array_list_test.c.o

.PHONY : kernel/src/ds/test/u8_array_list_test.o

# target to build an object file
kernel/src/ds/test/u8_array_list_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/u8_array_list_test.c.o
.PHONY : kernel/src/ds/test/u8_array_list_test.c.o

kernel/src/ds/test/u8_array_list_test.i: kernel/src/ds/test/u8_array_list_test.c.i

.PHONY : kernel/src/ds/test/u8_array_list_test.i

# target to preprocess a source file
kernel/src/ds/test/u8_array_list_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/u8_array_list_test.c.i
.PHONY : kernel/src/ds/test/u8_array_list_test.c.i

kernel/src/ds/test/u8_array_list_test.s: kernel/src/ds/test/u8_array_list_test.c.s

.PHONY : kernel/src/ds/test/u8_array_list_test.s

# target to generate assembly for a file
kernel/src/ds/test/u8_array_list_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/u8_array_list_test.c.s
.PHONY : kernel/src/ds/test/u8_array_list_test.c.s

kernel/src/ds/test/vp_array_list_test.o: kernel/src/ds/test/vp_array_list_test.c.o

.PHONY : kernel/src/ds/test/vp_array_list_test.o

# target to build an object file
kernel/src/ds/test/vp_array_list_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_array_list_test.c.o
.PHONY : kernel/src/ds/test/vp_array_list_test.c.o

kernel/src/ds/test/vp_array_list_test.i: kernel/src/ds/test/vp_array_list_test.c.i

.PHONY : kernel/src/ds/test/vp_array_list_test.i

# target to preprocess a source file
kernel/src/ds/test/vp_array_list_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_array_list_test.c.i
.PHONY : kernel/src/ds/test/vp_array_list_test.c.i

kernel/src/ds/test/vp_array_list_test.s: kernel/src/ds/test/vp_array_list_test.c.s

.PHONY : kernel/src/ds/test/vp_array_list_test.s

# target to generate assembly for a file
kernel/src/ds/test/vp_array_list_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_array_list_test.c.s
.PHONY : kernel/src/ds/test/vp_array_list_test.c.s

kernel/src/ds/test/vp_singly_linked_list_test.o: kernel/src/ds/test/vp_singly_linked_list_test.c.o

.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.o

# target to build an object file
kernel/src/ds/test/vp_singly_linked_list_test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_singly_linked_list_test.c.o
.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.c.o

kernel/src/ds/test/vp_singly_linked_list_test.i: kernel/src/ds/test/vp_singly_linked_list_test.c.i

.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.i

# target to preprocess a source file
kernel/src/ds/test/vp_singly_linked_list_test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_singly_linked_list_test.c.i
.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.c.i

kernel/src/ds/test/vp_singly_linked_list_test.s: kernel/src/ds/test/vp_singly_linked_list_test.c.s

.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.s

# target to generate assembly for a file
kernel/src/ds/test/vp_singly_linked_list_test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/test/vp_singly_linked_list_test.c.s
.PHONY : kernel/src/ds/test/vp_singly_linked_list_test.c.s

kernel/src/ds/u8_array_list.o: kernel/src/ds/u8_array_list.c.o

.PHONY : kernel/src/ds/u8_array_list.o

# target to build an object file
kernel/src/ds/u8_array_list.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/u8_array_list.c.o
.PHONY : kernel/src/ds/u8_array_list.c.o

kernel/src/ds/u8_array_list.i: kernel/src/ds/u8_array_list.c.i

.PHONY : kernel/src/ds/u8_array_list.i

# target to preprocess a source file
kernel/src/ds/u8_array_list.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/u8_array_list.c.i
.PHONY : kernel/src/ds/u8_array_list.c.i

kernel/src/ds/u8_array_list.s: kernel/src/ds/u8_array_list.c.s

.PHONY : kernel/src/ds/u8_array_list.s

# target to generate assembly for a file
kernel/src/ds/u8_array_list.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/u8_array_list.c.s
.PHONY : kernel/src/ds/u8_array_list.c.s

kernel/src/ds/vp_array_list.o: kernel/src/ds/vp_array_list.c.o

.PHONY : kernel/src/ds/vp_array_list.o

# target to build an object file
kernel/src/ds/vp_array_list.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_array_list.c.o
.PHONY : kernel/src/ds/vp_array_list.c.o

kernel/src/ds/vp_array_list.i: kernel/src/ds/vp_array_list.c.i

.PHONY : kernel/src/ds/vp_array_list.i

# target to preprocess a source file
kernel/src/ds/vp_array_list.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_array_list.c.i
.PHONY : kernel/src/ds/vp_array_list.c.i

kernel/src/ds/vp_array_list.s: kernel/src/ds/vp_array_list.c.s

.PHONY : kernel/src/ds/vp_array_list.s

# target to generate assembly for a file
kernel/src/ds/vp_array_list.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_array_list.c.s
.PHONY : kernel/src/ds/vp_array_list.c.s

kernel/src/ds/vp_singly_linked_list.o: kernel/src/ds/vp_singly_linked_list.c.o

.PHONY : kernel/src/ds/vp_singly_linked_list.o

# target to build an object file
kernel/src/ds/vp_singly_linked_list.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_singly_linked_list.c.o
.PHONY : kernel/src/ds/vp_singly_linked_list.c.o

kernel/src/ds/vp_singly_linked_list.i: kernel/src/ds/vp_singly_linked_list.c.i

.PHONY : kernel/src/ds/vp_singly_linked_list.i

# target to preprocess a source file
kernel/src/ds/vp_singly_linked_list.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_singly_linked_list.c.i
.PHONY : kernel/src/ds/vp_singly_linked_list.c.i

kernel/src/ds/vp_singly_linked_list.s: kernel/src/ds/vp_singly_linked_list.c.s

.PHONY : kernel/src/ds/vp_singly_linked_list.s

# target to generate assembly for a file
kernel/src/ds/vp_singly_linked_list.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/ds/vp_singly_linked_list.c.s
.PHONY : kernel/src/ds/vp_singly_linked_list.c.s

kernel/src/fs/file.o: kernel/src/fs/file.c.o

.PHONY : kernel/src/fs/file.o

# target to build an object file
kernel/src/fs/file.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/file.c.o
.PHONY : kernel/src/fs/file.c.o

kernel/src/fs/file.i: kernel/src/fs/file.c.i

.PHONY : kernel/src/fs/file.i

# target to preprocess a source file
kernel/src/fs/file.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/file.c.i
.PHONY : kernel/src/fs/file.c.i

kernel/src/fs/file.s: kernel/src/fs/file.c.s

.PHONY : kernel/src/fs/file.s

# target to generate assembly for a file
kernel/src/fs/file.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/file.c.s
.PHONY : kernel/src/fs/file.c.s

kernel/src/fs/inode.o: kernel/src/fs/inode.c.o

.PHONY : kernel/src/fs/inode.o

# target to build an object file
kernel/src/fs/inode.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/inode.c.o
.PHONY : kernel/src/fs/inode.c.o

kernel/src/fs/inode.i: kernel/src/fs/inode.c.i

.PHONY : kernel/src/fs/inode.i

# target to preprocess a source file
kernel/src/fs/inode.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/inode.c.i
.PHONY : kernel/src/fs/inode.c.i

kernel/src/fs/inode.s: kernel/src/fs/inode.c.s

.PHONY : kernel/src/fs/inode.s

# target to generate assembly for a file
kernel/src/fs/inode.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/inode.c.s
.PHONY : kernel/src/fs/inode.c.s

kernel/src/fs/path.o: kernel/src/fs/path.c.o

.PHONY : kernel/src/fs/path.o

# target to build an object file
kernel/src/fs/path.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/path.c.o
.PHONY : kernel/src/fs/path.c.o

kernel/src/fs/path.i: kernel/src/fs/path.c.i

.PHONY : kernel/src/fs/path.i

# target to preprocess a source file
kernel/src/fs/path.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/path.c.i
.PHONY : kernel/src/fs/path.c.i

kernel/src/fs/path.s: kernel/src/fs/path.c.s

.PHONY : kernel/src/fs/path.s

# target to generate assembly for a file
kernel/src/fs/path.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/path.c.s
.PHONY : kernel/src/fs/path.c.s

kernel/src/fs/test/test.o: kernel/src/fs/test/test.c.o

.PHONY : kernel/src/fs/test/test.o

# target to build an object file
kernel/src/fs/test/test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test.c.o
.PHONY : kernel/src/fs/test/test.c.o

kernel/src/fs/test/test.i: kernel/src/fs/test/test.c.i

.PHONY : kernel/src/fs/test/test.i

# target to preprocess a source file
kernel/src/fs/test/test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test.c.i
.PHONY : kernel/src/fs/test/test.c.i

kernel/src/fs/test/test.s: kernel/src/fs/test/test.c.s

.PHONY : kernel/src/fs/test/test.s

# target to generate assembly for a file
kernel/src/fs/test/test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test.c.s
.PHONY : kernel/src/fs/test/test.c.s

kernel/src/fs/test/test_path.o: kernel/src/fs/test/test_path.c.o

.PHONY : kernel/src/fs/test/test_path.o

# target to build an object file
kernel/src/fs/test/test_path.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test_path.c.o
.PHONY : kernel/src/fs/test/test_path.c.o

kernel/src/fs/test/test_path.i: kernel/src/fs/test/test_path.c.i

.PHONY : kernel/src/fs/test/test_path.i

# target to preprocess a source file
kernel/src/fs/test/test_path.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test_path.c.i
.PHONY : kernel/src/fs/test/test_path.c.i

kernel/src/fs/test/test_path.s: kernel/src/fs/test/test_path.c.s

.PHONY : kernel/src/fs/test/test_path.s

# target to generate assembly for a file
kernel/src/fs/test/test_path.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/test/test_path.c.s
.PHONY : kernel/src/fs/test/test_path.c.s

kernel/src/fs/tmpfs/test/test.o: kernel/src/fs/tmpfs/test/test.c.o

.PHONY : kernel/src/fs/tmpfs/test/test.o

# target to build an object file
kernel/src/fs/tmpfs/test/test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/test/test.c.o
.PHONY : kernel/src/fs/tmpfs/test/test.c.o

kernel/src/fs/tmpfs/test/test.i: kernel/src/fs/tmpfs/test/test.c.i

.PHONY : kernel/src/fs/tmpfs/test/test.i

# target to preprocess a source file
kernel/src/fs/tmpfs/test/test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/test/test.c.i
.PHONY : kernel/src/fs/tmpfs/test/test.c.i

kernel/src/fs/tmpfs/test/test.s: kernel/src/fs/tmpfs/test/test.c.s

.PHONY : kernel/src/fs/tmpfs/test/test.s

# target to generate assembly for a file
kernel/src/fs/tmpfs/test/test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/test/test.c.s
.PHONY : kernel/src/fs/tmpfs/test/test.c.s

kernel/src/fs/tmpfs/tmpfs.o: kernel/src/fs/tmpfs/tmpfs.c.o

.PHONY : kernel/src/fs/tmpfs/tmpfs.o

# target to build an object file
kernel/src/fs/tmpfs/tmpfs.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/tmpfs.c.o
.PHONY : kernel/src/fs/tmpfs/tmpfs.c.o

kernel/src/fs/tmpfs/tmpfs.i: kernel/src/fs/tmpfs/tmpfs.c.i

.PHONY : kernel/src/fs/tmpfs/tmpfs.i

# target to preprocess a source file
kernel/src/fs/tmpfs/tmpfs.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/tmpfs.c.i
.PHONY : kernel/src/fs/tmpfs/tmpfs.c.i

kernel/src/fs/tmpfs/tmpfs.s: kernel/src/fs/tmpfs/tmpfs.c.s

.PHONY : kernel/src/fs/tmpfs/tmpfs.s

# target to generate assembly for a file
kernel/src/fs/tmpfs/tmpfs.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/tmpfs/tmpfs.c.s
.PHONY : kernel/src/fs/tmpfs/tmpfs.c.s

kernel/src/fs/vfs.o: kernel/src/fs/vfs.c.o

.PHONY : kernel/src/fs/vfs.o

# target to build an object file
kernel/src/fs/vfs.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/vfs.c.o
.PHONY : kernel/src/fs/vfs.c.o

kernel/src/fs/vfs.i: kernel/src/fs/vfs.c.i

.PHONY : kernel/src/fs/vfs.i

# target to preprocess a source file
kernel/src/fs/vfs.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/vfs.c.i
.PHONY : kernel/src/fs/vfs.c.i

kernel/src/fs/vfs.s: kernel/src/fs/vfs.c.s

.PHONY : kernel/src/fs/vfs.s

# target to generate assembly for a file
kernel/src/fs/vfs.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/fs/vfs.c.s
.PHONY : kernel/src/fs/vfs.c.s

kernel/src/klibc/alloc.o: kernel/src/klibc/alloc.c.o

.PHONY : kernel/src/klibc/alloc.o

# target to build an object file
kernel/src/klibc/alloc.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/alloc.c.o
.PHONY : kernel/src/klibc/alloc.c.o

kernel/src/klibc/alloc.i: kernel/src/klibc/alloc.c.i

.PHONY : kernel/src/klibc/alloc.i

# target to preprocess a source file
kernel/src/klibc/alloc.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/alloc.c.i
.PHONY : kernel/src/klibc/alloc.c.i

kernel/src/klibc/alloc.s: kernel/src/klibc/alloc.c.s

.PHONY : kernel/src/klibc/alloc.s

# target to generate assembly for a file
kernel/src/klibc/alloc.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/alloc.c.s
.PHONY : kernel/src/klibc/alloc.c.s

kernel/src/klibc/klibc.o: kernel/src/klibc/klibc.c.o

.PHONY : kernel/src/klibc/klibc.o

# target to build an object file
kernel/src/klibc/klibc.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/klibc.c.o
.PHONY : kernel/src/klibc/klibc.c.o

kernel/src/klibc/klibc.i: kernel/src/klibc/klibc.c.i

.PHONY : kernel/src/klibc/klibc.i

# target to preprocess a source file
kernel/src/klibc/klibc.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/klibc.c.i
.PHONY : kernel/src/klibc/klibc.c.i

kernel/src/klibc/klibc.s: kernel/src/klibc/klibc.c.s

.PHONY : kernel/src/klibc/klibc.s

# target to generate assembly for a file
kernel/src/klibc/klibc.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/klibc.c.s
.PHONY : kernel/src/klibc/klibc.c.s

kernel/src/klibc/mem.o: kernel/src/klibc/mem.c.o

.PHONY : kernel/src/klibc/mem.o

# target to build an object file
kernel/src/klibc/mem.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/mem.c.o
.PHONY : kernel/src/klibc/mem.c.o

kernel/src/klibc/mem.i: kernel/src/klibc/mem.c.i

.PHONY : kernel/src/klibc/mem.i

# target to preprocess a source file
kernel/src/klibc/mem.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/mem.c.i
.PHONY : kernel/src/klibc/mem.c.i

kernel/src/klibc/mem.s: kernel/src/klibc/mem.c.s

.PHONY : kernel/src/klibc/mem.s

# target to generate assembly for a file
kernel/src/klibc/mem.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/mem.c.s
.PHONY : kernel/src/klibc/mem.c.s

kernel/src/klibc/printf.o: kernel/src/klibc/printf.c.o

.PHONY : kernel/src/klibc/printf.o

# target to build an object file
kernel/src/klibc/printf.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/printf.c.o
.PHONY : kernel/src/klibc/printf.c.o

kernel/src/klibc/printf.i: kernel/src/klibc/printf.c.i

.PHONY : kernel/src/klibc/printf.i

# target to preprocess a source file
kernel/src/klibc/printf.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/printf.c.i
.PHONY : kernel/src/klibc/printf.c.i

kernel/src/klibc/printf.s: kernel/src/klibc/printf.c.s

.PHONY : kernel/src/klibc/printf.s

# target to generate assembly for a file
kernel/src/klibc/printf.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/printf.c.s
.PHONY : kernel/src/klibc/printf.c.s

kernel/src/klibc/string.o: kernel/src/klibc/string.c.o

.PHONY : kernel/src/klibc/string.o

# target to build an object file
kernel/src/klibc/string.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/string.c.o
.PHONY : kernel/src/klibc/string.c.o

kernel/src/klibc/string.i: kernel/src/klibc/string.c.i

.PHONY : kernel/src/klibc/string.i

# target to preprocess a source file
kernel/src/klibc/string.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/string.c.i
.PHONY : kernel/src/klibc/string.c.i

kernel/src/klibc/string.s: kernel/src/klibc/string.c.s

.PHONY : kernel/src/klibc/string.s

# target to generate assembly for a file
kernel/src/klibc/string.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/klibc/string.c.s
.PHONY : kernel/src/klibc/string.c.s

kernel/src/test/test.o: kernel/src/test/test.c.o

.PHONY : kernel/src/test/test.o

# target to build an object file
kernel/src/test/test.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/test/test.c.o
.PHONY : kernel/src/test/test.c.o

kernel/src/test/test.i: kernel/src/test/test.c.i

.PHONY : kernel/src/test/test.i

# target to preprocess a source file
kernel/src/test/test.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/test/test.c.i
.PHONY : kernel/src/test/test.c.i

kernel/src/test/test.s: kernel/src/test/test.c.s

.PHONY : kernel/src/test/test.s

# target to generate assembly for a file
kernel/src/test/test.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/test/test.c.s
.PHONY : kernel/src/test/test.c.s

kernel/src/vm/asid_allocator.o: kernel/src/vm/asid_allocator.c.o

.PHONY : kernel/src/vm/asid_allocator.o

# target to build an object file
kernel/src/vm/asid_allocator.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/asid_allocator.c.o
.PHONY : kernel/src/vm/asid_allocator.c.o

kernel/src/vm/asid_allocator.i: kernel/src/vm/asid_allocator.c.i

.PHONY : kernel/src/vm/asid_allocator.i

# target to preprocess a source file
kernel/src/vm/asid_allocator.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/asid_allocator.c.i
.PHONY : kernel/src/vm/asid_allocator.c.i

kernel/src/vm/asid_allocator.s: kernel/src/vm/asid_allocator.c.s

.PHONY : kernel/src/vm/asid_allocator.s

# target to generate assembly for a file
kernel/src/vm/asid_allocator.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/asid_allocator.c.s
.PHONY : kernel/src/vm/asid_allocator.c.s

kernel/src/vm/pmm.o: kernel/src/vm/pmm.c.o

.PHONY : kernel/src/vm/pmm.o

# target to build an object file
kernel/src/vm/pmm.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/pmm.c.o
.PHONY : kernel/src/vm/pmm.c.o

kernel/src/vm/pmm.i: kernel/src/vm/pmm.c.i

.PHONY : kernel/src/vm/pmm.i

# target to preprocess a source file
kernel/src/vm/pmm.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/pmm.c.i
.PHONY : kernel/src/vm/pmm.c.i

kernel/src/vm/pmm.s: kernel/src/vm/pmm.c.s

.PHONY : kernel/src/vm/pmm.s

# target to generate assembly for a file
kernel/src/vm/pmm.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/pmm.c.s
.PHONY : kernel/src/vm/pmm.c.s

kernel/src/vm/test/test_asid.o: kernel/src/vm/test/test_asid.c.o

.PHONY : kernel/src/vm/test/test_asid.o

# target to build an object file
kernel/src/vm/test/test_asid.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_asid.c.o
.PHONY : kernel/src/vm/test/test_asid.c.o

kernel/src/vm/test/test_asid.i: kernel/src/vm/test/test_asid.c.i

.PHONY : kernel/src/vm/test/test_asid.i

# target to preprocess a source file
kernel/src/vm/test/test_asid.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_asid.c.i
.PHONY : kernel/src/vm/test/test_asid.c.i

kernel/src/vm/test/test_asid.s: kernel/src/vm/test/test_asid.c.s

.PHONY : kernel/src/vm/test/test_asid.s

# target to generate assembly for a file
kernel/src/vm/test/test_asid.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_asid.c.s
.PHONY : kernel/src/vm/test/test_asid.c.s

kernel/src/vm/test/test_pagealloc2.o: kernel/src/vm/test/test_pagealloc2.c.o

.PHONY : kernel/src/vm/test/test_pagealloc2.o

# target to build an object file
kernel/src/vm/test/test_pagealloc2.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_pagealloc2.c.o
.PHONY : kernel/src/vm/test/test_pagealloc2.c.o

kernel/src/vm/test/test_pagealloc2.i: kernel/src/vm/test/test_pagealloc2.c.i

.PHONY : kernel/src/vm/test/test_pagealloc2.i

# target to preprocess a source file
kernel/src/vm/test/test_pagealloc2.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_pagealloc2.c.i
.PHONY : kernel/src/vm/test/test_pagealloc2.c.i

kernel/src/vm/test/test_pagealloc2.s: kernel/src/vm/test/test_pagealloc2.c.s

.PHONY : kernel/src/vm/test/test_pagealloc2.s

# target to generate assembly for a file
kernel/src/vm/test/test_pagealloc2.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_pagealloc2.c.s
.PHONY : kernel/src/vm/test/test_pagealloc2.c.s

kernel/src/vm/test/test_vm2.o: kernel/src/vm/test/test_vm2.c.o

.PHONY : kernel/src/vm/test/test_vm2.o

# target to build an object file
kernel/src/vm/test/test_vm2.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_vm2.c.o
.PHONY : kernel/src/vm/test/test_vm2.c.o

kernel/src/vm/test/test_vm2.i: kernel/src/vm/test/test_vm2.c.i

.PHONY : kernel/src/vm/test/test_vm2.i

# target to preprocess a source file
kernel/src/vm/test/test_vm2.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_vm2.c.i
.PHONY : kernel/src/vm/test/test_vm2.c.i

kernel/src/vm/test/test_vm2.s: kernel/src/vm/test/test_vm2.c.s

.PHONY : kernel/src/vm/test/test_vm2.s

# target to generate assembly for a file
kernel/src/vm/test/test_vm2.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/test/test_vm2.c.s
.PHONY : kernel/src/vm/test/test_vm2.c.s

kernel/src/vm/vas2.o: kernel/src/vm/vas2.c.o

.PHONY : kernel/src/vm/vas2.o

# target to build an object file
kernel/src/vm/vas2.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vas2.c.o
.PHONY : kernel/src/vm/vas2.c.o

kernel/src/vm/vas2.i: kernel/src/vm/vas2.c.i

.PHONY : kernel/src/vm/vas2.i

# target to preprocess a source file
kernel/src/vm/vas2.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vas2.c.i
.PHONY : kernel/src/vm/vas2.c.i

kernel/src/vm/vas2.s: kernel/src/vm/vas2.c.s

.PHONY : kernel/src/vm/vas2.s

# target to generate assembly for a file
kernel/src/vm/vas2.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vas2.c.s
.PHONY : kernel/src/vm/vas2.c.s

kernel/src/vm/vm2.o: kernel/src/vm/vm2.c.o

.PHONY : kernel/src/vm/vm2.o

# target to build an object file
kernel/src/vm/vm2.c.o:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vm2.c.o
.PHONY : kernel/src/vm/vm2.c.o

kernel/src/vm/vm2.i: kernel/src/vm/vm2.c.i

.PHONY : kernel/src/vm/vm2.i

# target to preprocess a source file
kernel/src/vm/vm2.c.i:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vm2.c.i
.PHONY : kernel/src/vm/vm2.c.i

kernel/src/vm/vm2.s: kernel/src/vm/vm2.c.s

.PHONY : kernel/src/vm/vm2.s

# target to generate assembly for a file
kernel/src/vm/vm2.c.s:
	$(MAKE) -f CMakeFiles/course_os.dir/build.make CMakeFiles/course_os.dir/kernel/src/vm/vm2.c.s
.PHONY : kernel/src/vm/vm2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... course_os"
	@echo "... edit_cache"
	@echo "... kernel/src/allocator/allocator.o"
	@echo "... kernel/src/allocator/allocator.i"
	@echo "... kernel/src/allocator/allocator.s"
	@echo "... kernel/src/allocator/llist.o"
	@echo "... kernel/src/allocator/llist.i"
	@echo "... kernel/src/allocator/llist.s"
	@echo "... kernel/src/allocator/mem_alloc.o"
	@echo "... kernel/src/allocator/mem_alloc.i"
	@echo "... kernel/src/allocator/mem_alloc.s"
	@echo "... kernel/src/allocator/test/test_allocator.o"
	@echo "... kernel/src/allocator/test/test_allocator.i"
	@echo "... kernel/src/allocator/test/test_allocator.s"
	@echo "... kernel/src/common/hardwareinfo.o"
	@echo "... kernel/src/common/hardwareinfo.i"
	@echo "... kernel/src/common/hardwareinfo.s"
	@echo "... kernel/src/common/interrupt.o"
	@echo "... kernel/src/common/interrupt.i"
	@echo "... kernel/src/common/interrupt.s"
	@echo "... kernel/src/common/start.o"
	@echo "... kernel/src/common/start.i"
	@echo "... kernel/src/common/start.s"
	@echo "... kernel/src/drivers/chipset/bcm2835/bcm2835.o"
	@echo "... kernel/src/drivers/chipset/bcm2835/bcm2835.i"
	@echo "... kernel/src/drivers/chipset/bcm2835/bcm2835.s"
	@echo "... kernel/src/drivers/chipset/bcm2836/bcm2836.o"
	@echo "... kernel/src/drivers/chipset/bcm2836/bcm2836.i"
	@echo "... kernel/src/drivers/chipset/bcm2836/bcm2836.s"
	@echo "... kernel/src/drivers/chipset/bcm2836/timer.o"
	@echo "... kernel/src/drivers/chipset/bcm2836/timer.i"
	@echo "... kernel/src/drivers/chipset/bcm2836/timer.s"
	@echo "... kernel/src/drivers/chipset/bcm2836/uart.o"
	@echo "... kernel/src/drivers/chipset/bcm2836/uart.i"
	@echo "... kernel/src/drivers/chipset/bcm2836/uart.s"
	@echo "... kernel/src/drivers/chipset/chipset.o"
	@echo "... kernel/src/drivers/chipset/chipset.i"
	@echo "... kernel/src/drivers/chipset/chipset.s"
	@echo "... kernel/src/drivers/mmci/mmci.o"
	@echo "... kernel/src/drivers/mmci/mmci.i"
	@echo "... kernel/src/drivers/mmci/mmci.s"
	@echo "... kernel/src/ds/bpf/HashMap.o"
	@echo "... kernel/src/ds/bpf/HashMap.i"
	@echo "... kernel/src/ds/bpf/HashMap.s"
	@echo "... kernel/src/ds/bpf/test/hashmap_test.o"
	@echo "... kernel/src/ds/bpf/test/hashmap_test.i"
	@echo "... kernel/src/ds/bpf/test/hashmap_test.s"
	@echo "... kernel/src/ds/priority_queue.o"
	@echo "... kernel/src/ds/priority_queue.i"
	@echo "... kernel/src/ds/priority_queue.s"
	@echo "... kernel/src/ds/qstr.o"
	@echo "... kernel/src/ds/qstr.i"
	@echo "... kernel/src/ds/qstr.s"
	@echo "... kernel/src/ds/test/priority_queue_test.o"
	@echo "... kernel/src/ds/test/priority_queue_test.i"
	@echo "... kernel/src/ds/test/priority_queue_test.s"
	@echo "... kernel/src/ds/test/qstr_test.o"
	@echo "... kernel/src/ds/test/qstr_test.i"
	@echo "... kernel/src/ds/test/qstr_test.s"
	@echo "... kernel/src/ds/test/u8_array_list_test.o"
	@echo "... kernel/src/ds/test/u8_array_list_test.i"
	@echo "... kernel/src/ds/test/u8_array_list_test.s"
	@echo "... kernel/src/ds/test/vp_array_list_test.o"
	@echo "... kernel/src/ds/test/vp_array_list_test.i"
	@echo "... kernel/src/ds/test/vp_array_list_test.s"
	@echo "... kernel/src/ds/test/vp_singly_linked_list_test.o"
	@echo "... kernel/src/ds/test/vp_singly_linked_list_test.i"
	@echo "... kernel/src/ds/test/vp_singly_linked_list_test.s"
	@echo "... kernel/src/ds/u8_array_list.o"
	@echo "... kernel/src/ds/u8_array_list.i"
	@echo "... kernel/src/ds/u8_array_list.s"
	@echo "... kernel/src/ds/vp_array_list.o"
	@echo "... kernel/src/ds/vp_array_list.i"
	@echo "... kernel/src/ds/vp_array_list.s"
	@echo "... kernel/src/ds/vp_singly_linked_list.o"
	@echo "... kernel/src/ds/vp_singly_linked_list.i"
	@echo "... kernel/src/ds/vp_singly_linked_list.s"
	@echo "... kernel/src/fs/file.o"
	@echo "... kernel/src/fs/file.i"
	@echo "... kernel/src/fs/file.s"
	@echo "... kernel/src/fs/inode.o"
	@echo "... kernel/src/fs/inode.i"
	@echo "... kernel/src/fs/inode.s"
	@echo "... kernel/src/fs/path.o"
	@echo "... kernel/src/fs/path.i"
	@echo "... kernel/src/fs/path.s"
	@echo "... kernel/src/fs/test/test.o"
	@echo "... kernel/src/fs/test/test.i"
	@echo "... kernel/src/fs/test/test.s"
	@echo "... kernel/src/fs/test/test_path.o"
	@echo "... kernel/src/fs/test/test_path.i"
	@echo "... kernel/src/fs/test/test_path.s"
	@echo "... kernel/src/fs/tmpfs/test/test.o"
	@echo "... kernel/src/fs/tmpfs/test/test.i"
	@echo "... kernel/src/fs/tmpfs/test/test.s"
	@echo "... kernel/src/fs/tmpfs/tmpfs.o"
	@echo "... kernel/src/fs/tmpfs/tmpfs.i"
	@echo "... kernel/src/fs/tmpfs/tmpfs.s"
	@echo "... kernel/src/fs/vfs.o"
	@echo "... kernel/src/fs/vfs.i"
	@echo "... kernel/src/fs/vfs.s"
	@echo "... kernel/src/klibc/alloc.o"
	@echo "... kernel/src/klibc/alloc.i"
	@echo "... kernel/src/klibc/alloc.s"
	@echo "... kernel/src/klibc/klibc.o"
	@echo "... kernel/src/klibc/klibc.i"
	@echo "... kernel/src/klibc/klibc.s"
	@echo "... kernel/src/klibc/mem.o"
	@echo "... kernel/src/klibc/mem.i"
	@echo "... kernel/src/klibc/mem.s"
	@echo "... kernel/src/klibc/printf.o"
	@echo "... kernel/src/klibc/printf.i"
	@echo "... kernel/src/klibc/printf.s"
	@echo "... kernel/src/klibc/string.o"
	@echo "... kernel/src/klibc/string.i"
	@echo "... kernel/src/klibc/string.s"
	@echo "... kernel/src/test/test.o"
	@echo "... kernel/src/test/test.i"
	@echo "... kernel/src/test/test.s"
	@echo "... kernel/src/vm/asid_allocator.o"
	@echo "... kernel/src/vm/asid_allocator.i"
	@echo "... kernel/src/vm/asid_allocator.s"
	@echo "... kernel/src/vm/pmm.o"
	@echo "... kernel/src/vm/pmm.i"
	@echo "... kernel/src/vm/pmm.s"
	@echo "... kernel/src/vm/test/test_asid.o"
	@echo "... kernel/src/vm/test/test_asid.i"
	@echo "... kernel/src/vm/test/test_asid.s"
	@echo "... kernel/src/vm/test/test_pagealloc2.o"
	@echo "... kernel/src/vm/test/test_pagealloc2.i"
	@echo "... kernel/src/vm/test/test_pagealloc2.s"
	@echo "... kernel/src/vm/test/test_vm2.o"
	@echo "... kernel/src/vm/test/test_vm2.i"
	@echo "... kernel/src/vm/test/test_vm2.s"
	@echo "... kernel/src/vm/vas2.o"
	@echo "... kernel/src/vm/vas2.i"
	@echo "... kernel/src/vm/vas2.s"
	@echo "... kernel/src/vm/vm2.o"
	@echo "... kernel/src/vm/vm2.i"
	@echo "... kernel/src/vm/vm2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

