#!/bin/bash
# this bash script will read all directories to find tests.
# it will make a list of tests and write this to test.c
# the makefile will run this file automatically while building,
# so all tests are automatically executed.

# https://www.gnu.org/software/coreutils/manual/html_node/Random-sources.html
get_seeded_random()
{
    RANDOM=$1
    while true
    do
    echo "$RANDOM" || exit
    done
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# clear the file
echo -n "" > "$DIR/test.c"

echo "
// DO NOT EDIT
// this file is generated by generate_tests.sh

#ifdef ENABLE_TESTS

#include <stdio.h>
#include <interrupt.h>
#include <test.h>
#include <allocator.h>

size_t global_counter = 0;

" >> "$DIR/test.c"

echo "Seed used for test order randomization: $1"
#TESTFNS=$(grep -hr --include "*.c" -oP "(?<=TEST_CREATE\()(.*)(?=,)")
TESTFNS=$(grep -hr --include "*.c" -vP "^\s*\/\/.+" | grep -oP "(?<=TEST_CREATE\()(.*)(?=,)" | sort -R --random-source=<(get_seeded_random $1))

for FNNAME in $TESTFNS
do
  echo "int test_$FNNAME();" >> "$DIR/test.c"
done

echo "void test_main(){" >> "$DIR/test.c"

len=0
for FNNAME in $TESTFNS
do
  echo "    if (!test_$FNNAME()) {return;}" >> "$DIR/test.c"
  ((len++))
done


# shellcheck disable=SC2028
echo "
    buddy_status(mem_get_allocator());
  kprintf(\"TESTS COMPLETE. Passed %i tests\n\", $len);
  //SemihostingCall(ApplicationExit);
}
#endif
" >> "$DIR/test.c"
