#!/bin/bash
# this bash script will read all directories to find tests.
# it will make a list of tests and write this to test.c
# the makefile will run this file automatically while building,
# so all tests are automatically executed.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# clear the file
echo -n "" > "$DIR/test.c"

echo "
// DO NOT EDIT
// this file is generated by generate_tests.sh

#include <stdio.h>

" >> "$DIR/test.c"

TESTFNS=$(grep -hr --include "*.c" -oP "(?<=TEST_CREATE\()(.*)(?=,)")

for FNNAME in $TESTFNS
do
  echo "int test_$FNNAME();" >> "$DIR/test.c"
done

echo "void test_main(){" >> "$DIR/test.c"

for FNNAME in $TESTFNS
do
  echo "    if (!test_$FNNAME()) {return;}" >> "$DIR/test.c"
done


echo "
  os_printf(\"TESTS COMPLETE\n\");
}" >> "$DIR/test.c"