
// DO NOT EDIT
// this file is generated by generate_tests.sh

#include <stdio.h>


int test_first();
int test_second();
void test_main(){
    if (!test_first()) {return;}
    if (!test_second()) {return;}

  os_printf("TESTS COMPLETE\n");
}
