name: course_os test suite

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build -t course_os .

      - name: test
        run: docker run course_os sh -c 'cd build && ninja run-test'
